version: '3.8'

# 🚀 Docker Compose для локальной разработки Aisha Bot
# Версия: 2.0 (2025-06-11)
# Использует внешние сервисы и минимальную конфигурацию

services:
  # 🤖 Основной бот для разработки
  aisha-bot-dev:
    build:
      context: .
      dockerfile: docker/Dockerfile.bot
    container_name: aisha-bot-dev
    environment:
      # Основные настройки
      - PYTHONPATH=/app
      - INSTANCE_ID=bot-dev
      - BOT_MODE=polling
      - SET_POLLING=true
      
      # API ключи (из .env файла)
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - FAL_API_KEY=${FAL_API_KEY}
      
      # Внешние сервисы (реальные)
      - POSTGRES_HOST=192.168.0.4
      - POSTGRES_PORT=5432
      - POSTGRES_DB=aisha
      - POSTGRES_USER=aisha_user
      - POSTGRES_PASSWORD=KbZZGJHX09KSH7r9ev4m
      
      - REDIS_HOST=192.168.0.3
      - REDIS_PORT=6379
      - REDIS_PASSWORD=wd7QuwAbG0wtyoOOw3Sm
      
      - MINIO_ENDPOINT=192.168.0.4:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=74rSbw9asQ1uMzcFeM5G
      - MINIO_SECURE=false
      
      # Разработческие настройки
      - DEBUG=true
      - LOG_LEVEL=DEBUG
      - AVATAR_TEST_MODE=true
      
      # FAL AI настройки
      - FAL_DEFAULT_QUALITY_PRESET=fast
      
    volumes:
      # Монтируем код для live reload
      - ./app:/app/app:ro
      - ./alembic:/app/alembic:ro
      - ./main.py:/app/main.py:ro
      
      # Логи и временные файлы
      - ./temp/logs:/app/logs
      - ./temp/storage:/app/storage
      
    ports:
      # Для отладки если потребуется
      - "8080:8080"
      
    healthcheck:
      test: ["CMD", "pgrep", "-f", "python"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
      
    restart: unless-stopped
    
    # Подключение к внешней сети для доступа к сервисам
    networks:
      - aisha_dev_network

  # 🌐 Webhook API для разработки (опционально)
  webhook-api-dev:
    build:
      context: .
      dockerfile: docker/Dockerfile.webhook
    container_name: webhook-api-dev
    environment:
      - PYTHONPATH=/app
      - DEBUG=true
      - LOG_LEVEL=DEBUG
      
      # Базы данных
      - POSTGRES_HOST=192.168.0.4
      - POSTGRES_PORT=5432
      - POSTGRES_DB=aisha
      - POSTGRES_USER=aisha_user
      - POSTGRES_PASSWORD=KbZZGJHX09KSH7r9ev4m
      
      - REDIS_HOST=192.168.0.3
      - REDIS_PORT=6379
      - REDIS_PASSWORD=wd7QuwAbG0wtyoOOw3Sm
      
    volumes:
      - ./api_server:/app/api_server:ro
      - ./app:/app/app:ro
      - ./temp/logs:/app/logs
      
    ports:
      - "8001:8000"
      
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
      
    restart: unless-stopped
    networks:
      - aisha_dev_network
      
    # Запускать только при необходимости
    profiles:
      - webhook

# 🌐 Сети
networks:
  aisha_dev_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/16

# 📁 Volumes для постоянного хранения
volumes:
  dev_logs:
    driver: local
  dev_storage:
    driver: local 