version: '3.8'

services:
  # ======================== APPLICATION SERVICES ONLY ========================
  
  aisha-bot:
    build:
      context: .
      dockerfile: docker/Dockerfile.bot
      target: development
    container_name: aisha-bot-dev
    restart: unless-stopped
    environment:
      # Подключение к внешним сервисам проекта
      - DATABASE_URL=postgresql+asyncpg://aisha:${POSTGRES_PASSWORD}@${DATABASE_HOST}:5432/aisha
      - REDIS_URL=redis://${REDIS_HOST}:6379/0
      - MINIO_ENDPOINT=${MINIO_ENDPOINT}
      - DEBUG=true
      - ENVIRONMENT=development
    env_file:
      - .env.docker.dev
    volumes:
      - .:/app
      - /app/__pycache__
      - ./logs:/app/logs
    networks:
      - aisha-dev-network
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; sys.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  aisha-api:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
      target: development
    container_name: aisha-api-dev
    restart: unless-stopped
    ports:
      - "8443:8000"
    environment:
      # Подключение к внешним сервисам проекта
      - DATABASE_URL=postgresql+asyncpg://aisha:${POSTGRES_PASSWORD}@${DATABASE_HOST}:5432/aisha_v2
      - REDIS_URL=redis://${REDIS_HOST}:6379/0
      - DEBUG=true
      - ENVIRONMENT=development
    env_file:
      - .env.docker.dev
    volumes:
      - ./api_server:/app/api_server
    command: uvicorn api_server.main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - aisha-dev-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  aisha-dev-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16 