"""add_unique_constraint_for_main_avatar

Revision ID: b2df0db38780
Revises: 9580f7970746
Create Date: 2025-01-24 16:42:49.123456+05:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2df0db38780'
down_revision: Union[str, None] = '9580f7970746'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Добавляем частичный уникальный индекс: только один основной аватар на пользователя
    # WHERE is_main = true гарантирует, что ограничение действует только для основных аватаров
    op.create_index(
        'idx_avatars_user_main_unique', 
        'avatars', 
        ['user_id'], 
        unique=True,
        postgresql_where=sa.text('is_main = true')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_avatars_user_main_unique', table_name='avatars')
    # ### end Alembic commands ###
