global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'postgres'
    static_configs:
      - targets: ['192.168.0.4:5432']
    metrics_path: '/metrics'

  - job_name: 'minio'
    static_configs:
      - targets: ['192.168.0.4:9000']
    metrics_path: '/minio/v2/metrics/cluster'

  - job_name: 'minio_test'
    static_configs:
      - targets: ['minio_test:9000']
    metrics_path: '/minio/v2/metrics/cluster'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'aisha_bot'
    static_configs:
      - targets: ['host.docker.internal:8000']
    metrics_path: '/metrics' 