"""add_is_main_field_to_avatars

Revision ID: 9580f7970746
Revises: 230ce2455211
Create Date: 2025-05-24 16:29:42.074888+05:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa# revision identifiers, used by Alembic.
revision: str = '9580f7970746'
down_revision: Union[str, None] = '230ce2455211'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = Nonedef upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('avatars', sa.Column('is_main', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('avatars', 'is_main')
    # ### end Alembic commands ###
