"""
Revision ID: 52081111f590
Revises: d7cece93c6d0
Create Date: 2025-05-18 13:11:33.722155+05:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52081111f590'
down_revision = 'd7cece93c6d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_avatar_photos', sa.Column('photo_hash', sa.String(length=32), nullable=False))
    op.create_index(op.f('ix_user_avatar_photos_photo_hash'), 'user_avatar_photos', ['photo_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_avatar_photos_photo_hash'), table_name='user_avatar_photos')
    op.drop_column('user_avatar_photos', 'photo_hash')
    # ### end Alembic commands ### 