"""
Revision ID: 785670270724
Revises: 92177b271237
Create Date: 2025-05-17 18:12:30.377118+05:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '785670270724'
down_revision = '92177b271237'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('language_code', sa.String(length=16), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(length=32), nullable=True))
    op.add_column('users', sa.Column('is_bot', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('is_premium', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('last_active_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('is_blocked', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('settings', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('extra_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'extra_data')
    op.drop_column('users', 'settings')
    op.drop_column('users', 'is_blocked')
    op.drop_column('users', 'last_active_at')
    op.drop_column('users', 'is_premium')
    op.drop_column('users', 'is_bot')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'language_code')
    # ### end Alembic commands ### 